# Service config
service:
  protocol: LIREST_GATEWAY_PROTOCOL
  host: LIREST_GATEWAY_HOST
  port: LIREST_GATEWAY_PORT
  path: LIREST_GATEWAY_PATH

# Lirest services info
microservices:
  # Email service
  lirestEmailService:
    name: LIREST_EMAIL_SERVICE_NAME
    protocol: LIREST_EMAIL_SERVICE_PROTOCOL
    host: LIREST_EMAIL_SERVICE_HOST
    port: LIREST_EMAIL_SERVICE_PORT
    path: LIREST_EMAIL_SERVICE_PATH
  # User service
  lirestUserService:
    name: LIREST_USER_SERVICE_NAME
    protocol: LIREST_USER_SERVICE_PROTOCOL
    host: LIREST_USER_SERVICE_HOST
    port: LIREST_USER_SERVICE_PORT
    path: LIREST_USER_SERVICE_PATH

logConfig:
  logLevel: LIREST_GATEWAY_LOG_LEVEL
