# Service config
service:
  name: lirest-gateway
  host: '127.0.0.1'
  port: 3020
  path: /api/v1/gateway

# Lirest services info
microservices:
  # User service
  lirestUserService:
    name: lirest-user-service
    protocol: http
    host: '127.0.0.1'
    port: 3001
    path: /api/v1/user
  lirestIam:
    name: lirest-iam
    protocol: http
    host: '127.0.0.1'
    port: 3030
    path: /api/v1/iam

logConfig:
  logLevel: debug
