# Service config
service:
  protocol: http
  host: 127.0.0.1
  port: 3020
  path: /api/v1/lirest/gateway

# Lirest services info
microservices:
  # Email service
  lirestEmailService:
    name: 'lirest-email-service'
    protocol: http
    host: 127.0.0.1
    port: 3010
    path: /api/v1/lirest/email
  # Customer service
  lirestUserService:
    name: 'lirest-user-service'
    protocol: http
    host: 127.0.0.1
    port: 3011
    path: /api/v1/lirest/user

logConfig:
  logLevel: debug
