# Service config
service:
  protocol: http
  host: 127.0.0.1
  port: 3020
  path: /api/v1/lirest/gateway

# Lirest services info
microservices:
  # Email service
  lirestEmailService:
    name: 'lirest-email-service'
    protocol: http
    host: 127.0.0.1
    port: 3010
    path: /api/v1/lirest/email
  # Customer service
  lirestCustomerService:
    name: 'lirest-customer-service'
    protocol: http
    host: 127.0.0.1
    port: 3011
    path: /api/v1/lirest/customer

logConfig:
  logLevel: debug

# Authentication and authorization config
keycloak:
  realm: lirest
  auth-server-url: http://
  bearer-only: false
  ssl-required: external
  confidential-port: 0
  resource: lirest-gateway
  credentials:
    secret: oiZ4T26acmPZMBzsOCLhW1Mf5FisPbUk
